# Forzar el renderizador de Vulkan en Sway
WLR_RENDERER=vulkan

# Habilitar decodificación de video por hardware en Vulkan (Intel)
ANV_DEBUG=video-decode

# Opcional: mejorar la estabilidad en algunos casos
# WLR_SCENE_DISABLE_DIRECT_SCANOUT=1
