
[theme]
theme = "plain"

[theme.overrides]
idle_bg = "#282828"
idle_fg = "#ebdbb2"
good_bg = "#282828"
good_fg = "#b8bb26"
warning_bg = "#282828"
warning_fg = "#fabd2f"
critical_bg = "#282828"
critical_fg = "#fb4934"
separator = " | "
separator_bg = "#282828"
separator_fg = "#504945"


[[block]]
block = "toggle"
format = "PAN [$icon]"
# Comando que IMPRIME "on" si el Bluetooth está encendido.
command_state = "rfkill list bluetooth | grep -q 'Soft blocked: no' && echo on"
command_off = "rfkill block bluetooth"
command_on = "rfkill unblock bluetooth"
icon_on = "toggle_on"
icon_off = "toggle_off"

[[block]]
block = "sound"
driver = "pipewire"
format = " VOL [$volume.eng(hide_unit:true)]|VOL [MUTED] "
click = [
    { button = "left", cmd = "pactl set-sink-mute @DEFAULT_SINK@ toggle" }
]

[[block]]
block = "sound"
driver = "pipewire"
device_kind = "source"
format = " MIC [$volume.eng(hide_unit:true)]|MIC [MUTED] "
click = [
    { button = "left", cmd = "pactl set-source-mute @DEFAULT_SOURCE@ toggle" }
]


[[block]]
block = "backlight"
format = "LIGHT [$brightness.eng(hide_unit:true)]"
minimum = 5
maximum = 75

[[block]]
block = "battery"
format = "DISCHARGING [$percentage.eng(hide_unit:true)]" 
charging_format = "CHARGING [$percentage.eng(hide_unit:true)] "
not_charging_format = "DISCHARGING [$percentage.eng(hide_unit:true)]"
full_format = "[CHARGED]"
missing_format = "[NOT FOUND]"
interval = 60

[[block]]
block = "time"
format = "TIME [$timestamp.datetime(f:'%H:%M')]"
interval = 60
